const images = {
    header: {
        logo: require('../../assets/media/images/nav_logo.svg').default,
        youtube:  require('../../assets/media/images/youtube.svg').default
    },
    footer: {
        youtube: require('../../assets/media/images/youtube-logo-colored.svg').default
    },
    body: {
        bell: require('../../assets/media/images/bell.svg').default,
        playBtn: require('../../assets/media/images/play button.svg').default,
        latestVideo: require('../../assets/media/images/latest video.svg').default,
        favicon: require('../../assets/media/images/favicon.svg').default,
        channel: require('../../assets/media/images/home-video-cover.svg').default,
        bgBoxes: require('../../assets/media/images/bg-boxes.svg').default,
        orgDiamond: require('../../assets/media/images/org-dimond.svg').default,
        flameImg: require('../../assets/media/images/flame-img.svg').default,
        m_icon1: require('../../assets/media/images/m_icon1.svg').default,
        m_icon2: require('../../assets/media/images/m_icon2.svg').default,
        m_icon3: require('../../assets/media/images/m_icon3.svg').default,
    },
    slider1: {
        slide1:  require('../../assets/media/slides/slider3/slide4.svg').default,
        slide2:  require('../../assets/media/slides/slider3/slide3.svg').default,
        slide3:  require('../../assets/media/slides/slider3/slide6.svg').default,
        slide4:  require('../../assets/media/slides/slider3/slide2.svg').default,
        slide5:  require('../../assets/media/slides/slider3/slide5.svg').default,
        slide6:  require('../../assets/media/slides/slider3/slide1.svg').default,
        slide7:  require('../../assets/media/slides/slider3/slide11.svg').default,
    },
    slider2: {
        slide1:  require('../../assets/media/slides/slider2/slide1.svg').default,
    },
    slider3: {
        slide1:  require('../../assets/media/slides/slider3/slide1.svg').default,
        slide2:  require('../../assets/media/slides/slider3/slide2.svg').default,
        slide3:  require('../../assets/media/slides/slider3/slide3.svg').default,
        slide4:  require('../../assets/media/slides/slider3/slide4.svg').default,
        slide5:  require('../../assets/media/slides/slider3/slide5.svg').default,
        slide6:  require('../../assets/media/slides/slider3/slide6.svg').default,
        slide7:  require('../../assets/media/slides/slider3/slide7.svg').default,
        slide8:  require('../../assets/media/slides/slider3/slide8.svg').default,
        slide9:  require('../../assets/media/slides/slider3/slide9.svg').default,
        slide10:  require('../../assets/media/slides/slider3/slide10.svg').default,
        slide11:  require('../../assets/media/slides/slider3/slide11.svg').default,
    },
    news: {
        news1: require('../../assets/media/news/news1.svg').default,
        news2: require('../../assets/media/news/news2.svg').default,
        news3: require('../../assets/media/news/news3.svg').default,
    },
    fShorts: {
        slide1:  require('../../assets/media/fShorts/slide1.svg').default,
        slide2:  require('../../assets/media/fShorts/slide2.svg').default,
        slide3:  require('../../assets/media/fShorts/slide3.svg').default,
        slide4:  require('../../assets/media/fShorts/slide4.svg').default,
        slide5:  require('../../assets/media/fShorts/slide5.svg').default,
        slide6:  require('../../assets/media/fShorts/slide6.svg').default,
        slide7:  require('../../assets/media/fShorts/slide7.svg').default,
        slide8:  require('../../assets/media/fShorts/slide8.svg').default,
        slide9:  require('../../assets/media/fShorts/slide9.svg').default,
        slide10:  require('../../assets/media/fShorts/slide10.svg').default,
        slide11:  require('../../assets/media/fShorts/slide11.svg').default,
        slide12:  require('../../assets/media/fShorts/slide12.svg').default,
        slide13:  require('../../assets/media/fShorts/slide13.svg').default,
        slide14:  require('../../assets/media/fShorts/slide14.svg').default,
        slide15:  require('../../assets/media/fShorts/slide15.svg').default,
        slide16:  require('../../assets/media/fShorts/slide16.svg').default,
        slide17:  require('../../assets/media/fShorts/slide17.svg').default,
        slide18:  require('../../assets/media/fShorts/slide18.svg').default,
        slide19:  require('../../assets/media/fShorts/slide19.svg').default,
        slide20:  require('../../assets/media/fShorts/slide20.svg').default,
        slide21:  require('../../assets/media/fShorts/slide21.svg').default,
        slide22:  require('../../assets/media/fShorts/slide22.svg').default,
        slide23:  require('../../assets/media/fShorts/slide23.svg').default,
        slide24:  require('../../assets/media/fShorts/slide24.svg').default,
        slide25:  require('../../assets/media/fShorts/slide25.svg').default,
        slide26:  require('../../assets/media/fShorts/slide26.svg').default,
        slide27:  require('../../assets/media/fShorts/slide27.svg').default,
        slide28:  require('../../assets/media/fShorts/slide28.svg').default,
        slide29:  require('../../assets/media/fShorts/slide29.svg').default,
        slide30:  require('../../assets/media/fShorts/slide30.svg').default,
    }
}

export default images