const images = {
    header: {
        logo: require('../../assets/media/images/nav_logo.svg').default,
        youtube:  require('../../assets/media/images/youtube.svg').default
    },
    footer: {
        youtube: require('../../assets/media/images/youtube-logo-colored.svg').default
    },
    body: {
        bell: require('../../assets/media/images/bell.svg').default,
        playBtn: require('../../assets/media/images/play button.svg').default,
        latestVideo: require('../../assets/media/images/latest video.svg').default,
        favicon: require('../../assets/media/images/favicon.svg').default,
        channel: require('../../assets/media/images/home-video-cover.svg').default,
        bgBoxes: require('../../assets/media/images/bg-boxes.svg').default,
        orgDiamond: require('../../assets/media/images/org-dimond.svg').default,
    },
    slider1: {
        slide1:  require('../../assets/media/slides/slider3/slide4.jpg'),
        slide2:  require('../../assets/media/slides/slider3/slide3.jpg'),
        slide3:  require('../../assets/media/slides/slider3/slide6.jpg'),
        slide4:  require('../../assets/media/slides/slider3/slide2.jpg'),
        slide5:  require('../../assets/media/slides/slider3/slide5.jpg'),
        slide6:  require('../../assets/media/slides/slider3/slide1.jpg'),
        slide7:  require('../../assets/media/slides/slider3/slide11.jpg'),
    },
    slider2: {
        slide1:  require('../../assets/media/slides/slider2/slide1.svg').default,
    },
    slider3: {
        slide1:  require('../../assets/media/slides/slider3/slide1.jpg'),
        slide2:  require('../../assets/media/slides/slider3/slide2.jpg'),
        slide3:  require('../../assets/media/slides/slider3/slide3.jpg'),
        slide4:  require('../../assets/media/slides/slider3/slide4.jpg'),
        slide5:  require('../../assets/media/slides/slider3/slide5.jpg'),
        slide6:  require('../../assets/media/slides/slider3/slide6.jpg'),
        slide7:  require('../../assets/media/slides/slider3/slide7.jpg'),
        slide8:  require('../../assets/media/slides/slider3/slide8.jpg'),
        slide9:  require('../../assets/media/slides/slider3/slide9.jpg'),
        slide10:  require('../../assets/media/slides/slider3/slide10.jpg'),
        slide11:  require('../../assets/media/slides/slider3/slide11.jpg'),
    },
    news: {
        news1: require('../../assets/media/news/news1.svg').default,
        news2: require('../../assets/media/news/news2.svg').default,
        news3: require('../../assets/media/news/news3.svg').default,
    },
    fShorts: {
        slide1:  require('../../assets/media/fShorts/slide1.jpg'),
        slide2:  require('../../assets/media/fShorts/slide2.jpg'),
        slide3:  require('../../assets/media/fShorts/slide3.jpg'),
        slide4:  require('../../assets/media/fShorts/slide4.jpg'),
        slide5:  require('../../assets/media/fShorts/slide5.jpg'),
        slide6:  require('../../assets/media/fShorts/slide6.jpg'),
        slide7:  require('../../assets/media/fShorts/slide7.jpg'),
        slide8:  require('../../assets/media/fShorts/slide8.jpg'),
        slide9:  require('../../assets/media/fShorts/slide9.jpg'),
        slide10:  require('../../assets/media/fShorts/slide10.jpg'),
        slide11:  require('../../assets/media/fShorts/slide11.jpg'),
        slide12:  require('../../assets/media/fShorts/slide12.jpg'),
        slide13:  require('../../assets/media/fShorts/slide13.jpg'),
        slide14:  require('../../assets/media/fShorts/slide14.jpg'),
        slide15:  require('../../assets/media/fShorts/slide15.jpg'),
        slide16:  require('../../assets/media/fShorts/slide16.jpg'),
        slide17:  require('../../assets/media/fShorts/slide17.jpg'),
        slide18:  require('../../assets/media/fShorts/slide18.jpg'),
        slide19:  require('../../assets/media/fShorts/slide19.jpg'),
        slide20:  require('../../assets/media/fShorts/slide20.svg').default,
        slide21:  require('../../assets/media/fShorts/slide21.jpg'),
        slide22:  require('../../assets/media/fShorts/slide22.svg').default,
        slide23:  require('../../assets/media/fShorts/slide23.jpg'),
        slide24:  require('../../assets/media/fShorts/slide24.jpg'),
        slide25:  require('../../assets/media/fShorts/slide25.jpg'),
        slide26:  require('../../assets/media/fShorts/slide26.jpg'),
        slide27:  require('../../assets/media/fShorts/slide27.svg').default,
        slide28:  require('../../assets/media/fShorts/slide28.jpg'),
        slide29:  require('../../assets/media/fShorts/slide29.jpg'),
        slide30:  require('../../assets/media/fShorts/slide30.jpg'),
    }
}

export default images